### ISSUE TITLE
Contact by twitter doesn't work for me

### ISSUE THREAD

**Issue by hanjoosten** [karreiro/karreiro.github.io#14]
Hi Guilherme,

I read your blogpost about [multiple DRD diagrams](https://karreiro.com/2020/10/13/dmn-editor-supports-multiple-diagrams-now.html). I have been trying this out myself, and have some questions about that. So I would like to get in touch with you. I tried to send you a DM via twitter, as suggested at the bottom of the blogpost. However, for some reason that is disabled. Maybe an online chat? Are you open to that?
Kind regards,
Han Joosten (han dot joosten dot han at gmail dot com)

**Comment by karreiro** [comment]
👋 @hanjoosten,

Apologies for the delay. I just fixed my Twitter, it should be working by now :) - thank you for reporting that! 🙇 

Also, I'm no longer a maintainer in the DMN editor project, so maybe I won't have the most updated information, still feel free to reach out :)
